### ISSUE TITLE
Cannot copy between a TensorFlowLite tensor with shape [1, 2] and a Java object with shape [1, 4]., null)

### ISSUE THREAD

**Issue by emailsubjekt** [shaqian/flutter_tflite#10] opened 2019-01-14 07:07 UTC
Hi, I’m using a graph.lite trained with 2 results and a labels.txt, I have managed to get the example working, however it works wonderfully while I’m using it and I can analyze and take as many pictures as I want, yet when I leave to another screen in the app and come back I get an error like the one below stating that somehow the Java object which had correctly worked and gave me a result on top of the taken image, has now changed from [1,2] to [1,4], what’s more interesting is that this discrepancy keeps growing as I leave and come back, as the next time it’s [1,6], the next [1,8], next [1,10] you get the picture, and it constantly keeps giving me this error and doesn’t go on to analyze the image therefore I get no results anymore. I have to close the app and start it again for tensorflow to work, then again if I leave to another screen and come back it starts the same cycle. Is this a bug or should I change something else? I have used either 224 or 299 for image size when preparing tflite, imageMean was 128 not 127.5 but I’ve tried changing that too without any results. I have tried modifying the variables numResults, imageMean, imageStd, image sizes in main and tflite.dart however I still get an error on second run. The only thing I didn’t try changing was threshold. Can you please help. This is the error I get below. Best regards

E/flutter (23306): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (23306): PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 2] and a Java object with shape [1, 4]., null)
E/flutter (23306): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (23306): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (23306): <asynchronous suspension>
E/flutter (23306): #2      Tflite.runModelOnImage (package:tflite/tflite.dart:33:27)
E/flutter (23306): <asynchronous suspension>
E/flutter (23306): #3      _MyAppState.recognizeImage (package:someApp_tabbed_activity/tflite/tflitemain.dart:74:37)
E/flutter (23306): <asynchronous suspension>
E/flutter (23306): #4      _MyAppState.getImage (package:someApp_tabbed_activity/tflite/tflitemain.dart:25:5)
E/flutter (23306): <asynchronous suspension>
E/flutter (23306): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (23306): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (23306): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (23306): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (23306): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (23306): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (23306): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
E/flutter (23306): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (23306): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (23306): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (23306): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (23306): #16     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (23306): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)

**Comment by shaqian** [comment] 2019-01-15 02:45
Thank you for the feedback.
Would it be convenient for you to provide a sample project that reproduces the issue?

**Comment by emailsubjekt** [comment] 2019-01-16 23:58
Hi, I used your example with no modifications, then modified it with the files I have and the above mentioned modifications I did made no difference to how the app reacted. It works when I first use it even with no modifications to your example code, but when I leave the screen to another screen in the app and come back and try to use it I get the error I wrote out. What I don't understand is how can it work if I have a .lite with 2 possible answers and the example has in one class a definition of numResults = 6 and in another numResults = 5, yet it still provides me a correct answer when using the app. 

I could remake the .lite for the project but you could remake it really easy too. I can't unfortunately send you the original as it's proprietary and from a client I'm making this for, but it's a .lite with 2 possible answers as is the accompanying txt file which has the names of the options written out. As I said the example works great, I get a result meaning the file I'm using works and has worked on an Android version perfectly. However, here I keep getting this error after using it going to another screen in the app and then coming back. 

Contact me if you need help with making a .lite file, I'll be happy to help you solve this...

**Comment by shaqian** [comment] 2019-01-20 09:50
Glad to know it works. 😃I will add the fix in the next version.

**Comment by emailsubjekt** [comment] 2019-03-01 02:53
I've tried version 1.0.1 What did you do, the import is red, I'm using 
Also, why isn't there an example what to write into pubspec, you write "Add tflite as a dependency in your pubspec.yaml file." and then it takes me to the general info about adding dependencies. I know that, how do I add yours?!?!
tflite: ^1.0.1  ??? Is that the right way? 

Also I had a calculation of the final output and showed the result on the screen, I updated to that 1.0.1 and now no screen result is showing. I'm working on another app now and don't have time to look into this but why would you change the output, now I have to do this again, not cool bro

**Comment by shaqian** [comment] 2019-03-01 04:59
There are some breaking changes since 1.0.0
https://github.com/shaqian/flutter_tflite#breaking-changes-since-100

I think you were using 0.0.2 or 0.0.3. The latest version that doesn't break your code might be 0.0.5. 
https://pub.dartlang.org/packages/tflite#-changelog-tab-

You can try fixing the version like `tflite: 0.0.5`, then run `flutter packages get`. If you still get red squiggly lines, go to `ios` folder and run `pod install`. 

Thanks,
Qian

**Comment by emailsubjekt** [comment] 2019-03-02 08:25
Ok, thanks for the answer I will look into it in a couple of days, keep up the great work! =)

**Comment by SergioBernal8** [comment] 2019-03-28 13:21
I had a similar bug!
After searching and searching I realized that the ".txt" files that I dowloaded from the Git for the assets  folder was incorrect. Then I fixed that and everything its working fine now!
By the way I'm using detectObjectOnImage with the model "SSDMobileNet" 
tflite version: 1.0.2

Hope it helps!!

**Comment by brunokitaka** [comment] 2019-05-16 02:09
I'm trying to use a tflite file that I trained myself and I'm having this error:

E/flutter (24486): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 9, 9, 30]., null)
E/flutter (24486): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (24486): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (24486): <asynchronous suspension>
E/flutter (24486): #2      Tflite.detectObjectOnFrame (package:tflite/tflite.dart:152:27)
E/flutter (24486): <asynchronous suspension>
E/flutter (24486): #3      _CameraState.initState.<anonymous closure>.<anonymous closure> (package:flutter_realtime_detection/camera.dart:50:20)
E/flutter (24486): #4      CameraController.startImageStream.<anonymous closure> (package:camera/camera.dart:353:20)
E/flutter (24486): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (24486): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (24486): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (24486): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (24486): #9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (24486): #10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (24486): #11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (24486): #12     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (24486): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24486): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24486): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24486): #16     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (24486): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24486): #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24486): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24486): #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (24486): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by emailsubjekt** [comment] 2019-05-25 01:00
> I'm trying to use a tflite file that I trained myself and I'm getting this error:
> 
> E/flutter (24486): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 9, 9, 30]., null)
> E/flutter (24486): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
> E/flutter (24486): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
> E/flutter (24486): 
> E/flutter (24486): #2 Tflite.detectObjectOnFrame (package:tflite/tflite.dart:152:27)
> E/flutter (24486): 
> E/flutter (24486): #3 _CameraState.initState.. (package:flutter_realtime_detection/camera.dart:50:20)
> E/flutter (24486): #4 CameraController.startImageStream. (package:camera/camera.dart:353:20)
> E/flutter (24486): #5 _rootRunUnary (dart:async/zone.dart:1132:38)
> E/flutter (24486): #6 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> E/flutter (24486): #7 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> E/flutter (24486): #8 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
> E/flutter (24486): #9 _DelayedData.perform (dart:async/stream_impl.dart:591:14)
> E/flutter (24486): #10 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
> E/flutter (24486): #11 _PendingEvents.schedule. (dart:async/stream_impl.dart:667:7)
> E/flutter (24486): #12 _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (24486): #13 _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (24486): #14 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (24486): #15 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
> E/flutter (24486): #16 _rootRun (dart:async/zone.dart:1124:13)
> E/flutter (24486): #17 _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (24486): #18 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (24486): #19 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
> E/flutter (24486): #20 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (24486): #21 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

Well, this is your problem --> Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 9, 9, 30]., null) - You've trained it wrong.

**Comment by shaqian** [comment] 2019-05-30 05:17
Archiving the thread as the original issue is fixed in new version. 

@brunokitaka Feel free to raise a new issue if you still get error with your model. 

Thanks,
Qian

**Closed** 2019-05-30 05:17 UTC
Labels: bug

**Comment by aakashganga** [comment] 2019-07-05 21:32
Hi I trained the Mobilenet model on certain domain specific images using transfer learning. But, when I try to run the model, I get "Cannot copy between a TensorFlowLite tensor with shape [1, 11] and a Java object with shape [1, 11, 4]". I have 11 classes in my dataset. How may I fix the issue?

**Comment by aakashganga** [comment] 2019-07-05 21:39
> After searching and searching I realized that the ".txt" files that I dowloaded from the Git for the assets folder was incorrect. Then I fixed that and everything its working fine now!

When you say the txt files were incorrect, what do you mean? Incorrect in what sense?

**Comment by rash1994** [comment] 2019-08-30 08:35
> > I'm trying to use a tflite file that I trained myself and I'm getting this error:
> > E/flutter (24486): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 9, 9, 30]., null)
> > E/flutter (24486): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
> > E/flutter (24486): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
> > E/flutter (24486):
> > E/flutter (24486): #2 Tflite.detectObjectOnFrame (package:tflite/tflite.dart:152:27)
> > E/flutter (24486):
> > E/flutter (24486): #3 _CameraState.initState.. (package:flutter_realtime_detection/camera.dart:50:20)
> > E/flutter (24486): #4 CameraController.startImageStream. (package:camera/camera.dart:353:20)
> > E/flutter (24486): #5 _rootRunUnary (dart:async/zone.dart:1132:38)
> > E/flutter (24486): #6 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> > E/flutter (24486): #7 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> > E/flutter (24486): #8 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
> > E/flutter (24486): #9 _DelayedData.perform (dart:async/stream_impl.dart:591:14)
> > E/flutter (24486): #10 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
> > E/flutter (24486): #11 _PendingEvents.schedule. (dart:async/stream_impl.dart:667:7)
> > E/flutter (24486): #12 _rootRun (dart:async/zone.dart:1120:38)
> > E/flutter (24486): #13 _CustomZone.run (dart:async/zone.dart:1021:19)
> > E/flutter (24486): #14 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> > E/flutter (24486): #15 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
> > E/flutter (24486): #16 _rootRun (dart:async/zone.dart:1124:13)
> > E/flutter (24486): #17 _CustomZone.run (dart:async/zone.dart:1021:19)
> > E/flutter (24486): #18 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> > E/flutter (24486): #19 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
> > E/flutter (24486): #20 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> > E/flutter (24486): #21 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> 
> Well, this is your problem --> Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 9, 9, 30]., null) - You've trained it wrong.

Can you tell trained it wrong meaning ? 
what is wrong is training?

**Comment by EyeSlash1998** [comment] 2020-05-05 17:49
> Hi I trained the Mobilenet model on certain domain specific images using transfer learning. But, when I try to run the model, I get "Cannot copy between a TensorFlowLite tensor with shape [1, 11] and a Java object with shape [1, 11, 4]". I have 11 classes in my dataset. How may I fix the issue?

Were you able to solve this issue, because even I'am facing an issue were I get the error "Cannot copy between a TensorFlow Lite tensor with shape [1,2535,9] and a java object with shape [1,13,13,45]".

**Comment by supermarille** [comment] 2020-05-11 09:34
Same issue here : 
`java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 1]`
I have only one class, I followed this tutorial https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md using bazel to convert to tflite. 
I understand that the second value of the shape should be the number of classes, but what are the other values ?

**Comment by rxsh96** [comment] 2020-05-26 01:35
I have the same problem: `Cannot copy between a TensorFlowLite tensor with shape [1, 1] and a Java object with shape [1, 2]`
I have MobileNetV2 as input layer, 1 flatten and 3 dense layers and then converted to tflite. I have 2 classes in my dataset. Is there some kind of limitation for tflite package does not work with custom models?

**Comment by shaharhn** [comment] 2020-08-15 10:45
Any solution ?

**Comment by nikunj5022** [comment] 2020-10-09 08:11
> > Hi I trained the Mobilenet model on certain domain specific images using transfer learning. But, when I try to run the model, I get "Cannot copy between a TensorFlowLite tensor with shape [1, 11] and a Java object with shape [1, 11, 4]". I have 11 classes in my dataset. How may I fix the issue?
> 
> Were you able to solve this issue, because even I'am facing an issue were I get the error "Cannot copy between a TensorFlow Lite tensor with shape [1,2535,9] and a java object with shape [1,13,13,45]".

Any solution?
