### ISSUE TITLE
Please add null safety

### ISSUE THREAD

**Issue by Abin-Thankachan** [shaqian/flutter_tflite#198] opened 2021-04-03 08:43 UTC

**Comment by ben-xD** [comment] 2021-04-08 01:40
@shaqian Is this a difficult challenge? I would be interested to try to do it :)

**Comment by shaqian** [comment] 2021-04-13 10:36
Hi, I received this PR and it's been merged to v1.1.2: https://github.com/shaqian/flutter_tflite/pull/196

Thanks,
Qian

**Comment by zxenonx** [comment] 2021-04-27 13:31
> Hi, I received this PR and it's been merged to v1.1.2: #196
> 
> Thanks,
> Qian

So the issue is resolved. It can be closed.

**Closed** 2021-05-08 06:56 UTC
